// =====================================================
//                 Players API Requests
// =====================================================


###

GET http://localhost:8080/api/players

###
// Getting exising player
GET http://localhost:8080/api/players/1

###
// Getting NOT exising player
GET http://localhost:8080/api/players/1000

###

POST http://localhost:8080/api/players
Content-Type: application/json

{
  "username": "The New Player",
  "image_file": "unknown.png"
}

###
// Updateing exising player

PUT http://localhost:8080/api/players/1
Content-Type: application/json

{
  "username": "The New Player USERNAME"
}

###
// Updateing NOT exising player

PUT http://localhost:8080/api/players/1000
Content-Type: application/json

{
  "username": "The New Player USERNAME"
}

###
// Deleting exising player

DELETE http://localhost:8080/api/players/1

###
// Deleting NOT exising player
DELETE http://localhost:8080/api/players/1000
