version: "3.9"


services:

  # RabbitMQ service instance being
  # Message queue receiver and sender
  rabbitmq:
    container_name: rabbitmq
    build:
      context: "./rabbitmq"
      dockerfile: "Dockerfile"
    networks:
      - internal_network

  # System database based on MariaDB image
  mariadb:
    container_name: mariadb
    build:
      context: "./mariadb"
      dockerfile: "Dockerfile"
    networks:
      - internal_network

  # Reverse proxy application being only
  # one container that user can connect to.
  # It determines which request goes to
  # which server (api gateway or frontend).
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: "./reverse_proxy"
      dockerfile: "Dockerfile"
    depends_on:
      - frontend
      - api_gateway
    ports:
      - "80:80"
    networks:
      - internal_network

  # Frontend flask application with
  # whole frontend webpage content.
  frontend:
    container_name: frontend
    build:
      context: "../"
      dockerfile: "./.docker/frontend/Dockerfile"
    networks:
      - internal_network

  # Gateway service being between
  # frontend and all backend services.
  api_gateway:
    container_name: api_gateway
    build:
      context: "./api_gateway"
      dockerfile: "Dockerfile"
    depends_on:
      - api_players
      - api_accounts
      - api_games
    networks:
    - internal_network

  # Api Players application which is used 
  # by frontend for players management.
  api_players:
    container_name: api_players
    build:
      context: "../"
      dockerfile: ".docker/api_players/Dockerfile"
    depends_on:
      - rabbitmq
      - mariadb
    networks:
      - internal_network

  # Api Games application which is used
  # by frontend for games management.
  api_games:
    container_name: api_games
    build:
      context: "../"
      dockerfile: ".docker/api_games/Dockerfile"
    depends_on:
      - rabbitmq
      - mariadb
    networks:
      - internal_network

  # Api Accounts application which is used
  # by frontend for accounts management.
  api_accounts:
    container_name: api_accounts
    build:
      context: "../"
      dockerfile: ".docker/api_accounts/Dockerfile"
    depends_on:
      - mariadb
    networks:
      - internal_network

# Internal network for all containers.
networks:
  internal_network: